# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cupOfTea' do
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GooglePlaces'

end
